NUMPY- numerical python Part-1

In [44]:
import numpy as np

In [45]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [46]:
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Dimensions in array

In [47]:
arr=np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


1 d arry

In [48]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


2d array

In [49]:
arr= np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [37]:
arr=np.array([[2.4,4.5,6.7],[1.2,2.3,8.9]])
print(arr)
print(arr.ndim)

[[2.4 4.5 6.7]
 [1.2 2.3 8.9]]
2


3d array

In [38]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [39]:
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[3,4,5]])
d=np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Create an arry with 5 dimension and verify that it has 5 dimensions:

In [40]:
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print('numberof dimension:',arr.ndim)

[[[[[1 2 3 4 5]]]]]
numberof dimension: 5


In [41]:
a=np.array([[[[[[1,2,3,4,5,6,7,8,9]]]]]])
print(a)
print(a.ndim)

[[[[[[1 2 3 4 5 6 7 8 9]]]]]]
6


indexing in 1d array

In [42]:
arr=np.array([1,2,3,4,5])
print(arr[3])

4


                         0       1
                       0,1,2    0,1,2
  indexing in 2d array-([1,2,2],[3,5,6])
                       



In [43]:
arr=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr[0,3])
print(arr[1,2])

40
80


additon of element between the  2d array

In [52]:
arr=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr[0,4]+arr[1,3])

140


access the 3d array

           0                1
    0          1        0       1
     0,1,2   0,1,2    0,1,2    0,1,2
([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])

In [54]:
d=np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
print(d[1,1,2])

9
